### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/repo#1]
- [x] fajnie by bylo, gdyby ta strona dobrze sie wyswietlala
- [x] dorzucilem pare zmian, rozejrzyj sie, co tu sie zadzialo
- [x] zaciagnij zmiany do siebie na kompa
- [x] domerguj brancha `test` do brancha `master`
- [x] wypushuj zmiany do repo zdalnego
